/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author tf872254
 */
public class VueGAWT extends java.awt.Frame implements Observer{

  
    /**
     * Creates new form VueGAWT
     */
    public VueGAWT() {
      
        /*
        this.addWindowListener(new WindowAdapter(){
           public void windowClosing(WindowEvent e){
           System.exit(0);
            }
        });
        */
        initComponents();
        this.setSize(400,400);
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suprrOrange = new javax.swing.JButton();
        ajoutOrange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        suprrOrange.setText("-");
        suprrOrange.setName("moins"); // NOI18N
        add(suprrOrange, java.awt.BorderLayout.SOUTH);

        ajoutOrange.setText("+");
        ajoutOrange.setName("plus"); // NOI18N
        add(ajoutOrange, java.awt.BorderLayout.NORTH);
        ajoutOrange.getAccessibleContext().setAccessibleName("ajoutOrange");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");
        add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGAWT().setVisible(true);
            }
        });
    }
    public void addController(Controller c){
        ajoutOrange.addActionListener(c);
        suprrOrange.addActionListener(c);
    }
    
    public void update(Observable o, Object arg) {
        jLabel1.setText(""+((Panier)o).getNbOrange());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutOrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton suprrOrange;
    // End of variables declaration//GEN-END:variables
}
